- cli.js
fix https://github.com/marckraw/sb-mig/issues/1
> [issue-1] Now, tasks are creating folders

- cli.js
- helpers/logger.js
- package-lock.json
- package.json
- restApi.js
fix https://github.com/marckraw/sb-mig/issues/2
> Issue 2 handling errors

- README.md
- cli.js
- config.js
- package-lock.json
- package.json
- restApi.js
fix https://github.com/marckraw/sb-mig/issues/9
> [#5] add experimental feature to download code from seed project

- CHANGELOG.md
- cli.js
- migrate.js
- package-lock.json
- package.json
fix https://github.com/marckraw/sb-mig/issues/18
> feature: Add selective component syncing

- CHANGELOG.md
- README.md
- config.js
- package-lock.json
- package.json
fix https://github.com/marckraw/sb-mig/issues/20
> Issue 20 custom config

- .github/workflows/npmpublish.yml
- CHANGELOG.md
- package-lock.json
- package.json
fix https://github.com/marckraw/sb-mig/issues/16
> Github action for publish

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/cli.js
- src/config.js
- src/discover.js
- src/migrate.js
fix: https://github.com/marckraw/sb-mig/issues/52
> Syncing components with .sb.js extension

- CHANGELOG.md
- package-lock.json
- package.json
- src/cli.js
- src/migrate.js
fix: https://github.com/marckraw/sb-mig/issues/62
> Add ability to --sync-all files with .sb.js extension

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/api/components.js
- src/api/mutateComponents.js
- src/api/presets.js
- src/cli.js
- src/migrate.js
fix: https://github.com/marckraw/sb-mig/issues/38 - by using storyblok-js-client which has request throttle implemented
fix: https://github.com/marckraw/sb-mig/issues/39
> Move requests to storyblok js client, add no-preset option to syncing components

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/api/components.js
- src/api/datasources.js
- src/api/index.js
- src/api/presets.js
- src/cli.js
- src/config.js
- src/discover.js
- src/migrate.js
fix: https://github.com/marckraw/sb-mig/issues/43
> Datasources api

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/api/index.js
- src/api/spaces.js
- src/cli.js
- src/config.js
- src/helpers/componentsFileGenerator.js
- src/helpers/files.js
- src/helpers/logger.js
- src/migrate.js
fix: https://github.com/marckraw/sb-mig/issues/23 - generate whole project
fix: https://github.com/marckraw/sb-mig/issues/61 - copy files from node_modules
> Generating full project from cli.

- CHANGELOG.md
- package-lock.json
- package.json
- src/cli.js
- src/helpers/files.js
fix https://github.com/marckraw/sb-mig/issues/45
> [WIP] Improve --add command and whole integration with scoped packages.

- CHANGELOG.md
- README.md
- package.json
- src/api/migrate.ts
- src/commands/sync.ts
- src/utils/discover.ts
fix: https://github.com/sb-mig/sb-mig/issues/109
> Syncing components with just package name

- CHANGELOG.md
- README.md
- package.json
- src/commands/backup.ts
- src/utils/others.ts
fix: https://github.com/sb-mig/sb-mig/issues/117
> fix: change filenames in backup module to support Windows filenames

- @sb-mig/plugin-add-components/src/commands/add.ts
- @sb-mig/sb-mig/README.md
- @sb-mig/sb-mig/src/config/StoryblokComponentsConfig.ts
- @sb-mig/sb-mig/src/utils/discover2.ts
fix: https://github.com/sb-mig/sb-mig/issues/132
> Documentation for tracking and fixing importing not extisting style files

- @sb-mig/sb-mig/README.md
- @sb-mig/sb-mig/src/api/migrate.ts
- @sb-mig/sb-mig/src/api/roles.ts
- @sb-mig/sb-mig/src/commands/backup.ts
- @sb-mig/sb-mig/src/commands/sync.ts
- @sb-mig/sb-mig/src/config/config.ts
- @sb-mig/sb-mig/src/utils/discover2.ts
Syncing Roles feature
fix: https://github.com/sb-mig/sb-mig/issues/139
> Sync roles

- @sb-mig/sb-mig/package.json
- yarn.lock
Fix Server-Side Request Forgery vulnerability on axios depency on storyblok-js-client package
> Update storyblok-js-client version

- src/api/componentPresets.ts
- src/api/components.ts
- src/api/datasources/datasources.ts
- src/api/migrate.ts
- src/api/plugins.ts
- src/api/presets.ts
- src/api/roles.ts
- src/api/stories.ts
- src/cli-descriptions.ts
- src/commands/backup.ts
- src/commands/migrate.ts
- src/config/config.ts
- src/config/helper.ts
- src/index.ts
- src/utils/discover.ts
- migration solution for components and its values
- add pagination to all request to get all items (some of them doesnt have pagination stuff from storyblok, created issue)
Issue in `storyblok-js-client`: https://github.com/storyblok/storyblok-js-client/issues/535
> Migration stories in regards to component

- package.json
- src/api/contentHubApi.ts
- src/api/data-migration/component-data-migration.ts
- src/api/migrate.ts
- src/api/stories.ts
- src/cli-descriptions.ts
- src/commands/backup.ts
- src/commands/migrate.ts
- src/commands/revert.ts
- src/commands/sync.ts
- src/config/config.ts
- src/config/helper.ts
- src/index.ts
- src/utils/discover.ts
- src/utils/files.ts
- src/utils/others.ts
- src/utils/sync-utils.ts
- yarn.lock
- some more improvements to migration
- improve and update documentation
- better backup command for all presets
> fix: migrating from space to space with migration file

- package.json
- src/api/components/components.ts
- src/api/datasources/datasources.ts
- src/api/migrate.ts
- src/api/utils/request.ts
- src/api/utils/resolverTransformations.ts
- src/cli/api-config.ts
- src/cli/cli-descriptions.ts
- src/cli/commands/ask.ts
- src/cli/index.ts
- src/cli/utils/discover.ts
- src/config/config.ts
- src/config/constants.ts
- src/config/defaultConfig.ts
- yarn.lock
Proposition: 
`main.resolvers.schema.sb.ts` - on the consumer side
```
import {SchemaGlobalResolvers} from "./resolvers.types";
const schemaGlobalResolvers: SchemaGlobalResolvers = {
componentNames: {
names: ['sb-section', 'sb-content-group-section'],
methods: {
extend: {
component_whitelist: ['custom-component', 'sb-conditional-form-show', 'sb-form-input']
}
}
},
}
export default schemaGlobalResolvers
```
This will modify (extend) `component_whitelist` for all components in the `componentNams['names']` list (so for `sb-section` and `sb-content-group-section`)
> Exploration of overwrite config file + a little bit of AI dropppiin

- src/api/stories/tree.ts
- src/cli/cli-descriptions.ts
- src/cli/commands/copy.ts
- src/cli/commands/sync.ts
- src/cli/index.ts
- src/cli/roles/sync.ts
- src/cli/utils/discover.ts
- src/utils/others.ts
https://www.loom.com/share/35c975ef91e1498f827b40062afefa8a?sid=78fabc5c-971f-4790-83c1-16284df4f425
https://www.loom.com/embed/d20f6386bdba40e9894e977871d5b0cb?sid=be297d3d-e2f6-43f0-ba9f-099cdcbc2390
> feat: advanced story copy between spaces

- src/config/constants.ts
as mentioned in the issue: https://github.com/sb-mig/sb-mig/issues/306
> fix: add asia pacific to regions
